version: '3.7'

services:
  container-backend-mysql:
      image: mysql:5.7
      container_name: "${COMPOSE_PROJECT_NAME_DB}"
      hostname: "${COMPOSE_PROJECT_NAME_DB}"
      environment:
        - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db_root_password
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD_FILE=/run/secrets/db_password
      restart: unless-stopped
      ports:
        - 127.0.0.1:${MYSQL_PORT1_TO_3306}:3306
        - 0.0.0.0:${MYSQL_PORT2_TO_3306}:3306
      volumes:
        - volumencode:/var/lib/mysql
      env_file:
        - ./.env_database
      secrets:
        - db_root_password
        - db_password
      networks:
        - proxynet

  container-backend-app:
      build:
        context: .
        args:
          UID: ${UID:-0}
          GID: ${GID:-0}
          UNAME: ${UNAME:-cvrt}
      links:
        - "container-backend-mysql:db"
      container_name: "${COMPOSE_PROJECT_NAME_APP}"
      hostname: "${COMPOSE_PROJECT_NAME_APP}"
      restart: unless-stopped
      volumes:
        - ../src:/var/www/html
      env_file:
        - ./.env_app
      ports:
        - ${APP_PORT1_TO_80}:80
        - ${APP_PORT2_TO_8080}:8080
      networks:
        - proxynet
      depends_on:
        - container-backend-mysql

secrets:
  db_root_password:
    file: db_root_password.txt
  db_password:
    file: db_password.txt
    
volumes:
  volumencode:
    name: ${COMPOSE_PROJECT_NAME_DB}-data
    external: false

networks:
  proxynet:
    name: shared_bridge
    driver: bridge
    
